version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: devdb
    ports:
      - "3306:3306"